default:
  image: gradle:jdk11

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - ./gradlew build-cs108

test-job1:
  stage: test
  script:
    - echo "Testing the game..."
    - ./gradlew test
